# Generated by Django 3.0 on 2019-12-09 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=300)),
                ('build_date', models.DateTimeField(verbose_name='date built')),
                ('idEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
